#!/bin/bash

# APGI Framework Deployment Automation Script
# Handles Docker deployment, environment setup, and service management

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DOCKER_IMAGE_NAME="apgi-framework"
DOCKER_CONTAINER_NAME="apgi-app"
DOCKER_TAG="latest"
ENVIRONMENT_FILE=".env"
COMPOSE_FILE="docker-compose.yml"

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo
}

# Function to check if Docker is available
check_docker() {
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed or not in PATH"
        exit 1
    fi
    
    if ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose is not installed or not in PATH"
        exit 1
    fi
    
    print_status "Docker and Docker Compose are available"
}

# Function to create environment file
create_env_file() {
    if [[ ! -f "$ENVIRONMENT_FILE" ]]; then
        print_status "Creating environment configuration file..."
        cat > "$ENVIRONMENT_FILE" << EOF
# APGI Framework Environment Configuration
# Generated by deployment script on $(date)

# Application Settings
APGI_ENV=production
APGI_DEBUG=false
APGI_LOG_LEVEL=INFO

# Database Settings
APGI_DB_PATH=/app/data/apgi.db
APGI_DB_BACKUP_PATH=/app/data/backups/

# GUI Settings
APGUI_THEME=dark
APGUI_FONT_SIZE=12
APGUI_WINDOW_WIDTH=1400
APGUI_WINDOW_HEIGHT=900

# Security Settings
APGI_SECRET_KEY=$(openssl rand -hex 32)
APGI_SESSION_TIMEOUT=3600

# Performance Settings
APGI_MAX_WORKERS=4
APGI_THREAD_POOL_SIZE=8
APGI_MEMORY_LIMIT=2g

# Data Paths
APGI_DATA_DIR=/app/data
APGI_OUTPUTS_DIR=/app/apgi_outputs
APGI_SESSIONS_DIR=/app/session_state
APGI_LOGS_DIR=/app/logs

# External Service URLs (if applicable)
# APGI_EEG_SERVICE_URL=http://eeg-service:8080
# APGI_PUPILLOMETRY_SERVICE_URL=http://pupillometry-service:8081

# Monitoring
APGI_METRICS_ENABLED=true
APGI_HEALTH_CHECK_INTERVAL=30
EOF
        print_status "Environment file created: $ENVIRONMENT_FILE"
        print_warning "Please review and modify the environment variables as needed"
    else
        print_status "Environment file already exists: $ENVIRONMENT_FILE"
    fi
}

# Function to create Docker Compose file
create_compose_file() {
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        print_status "Creating Docker Compose configuration..."
        cat > "$COMPOSE_FILE" << EOF
version: '3.8'

services:
  apgi-framework:
    build:
      context: .
      dockerfile: Dockerfile
    image: \${DOCKER_IMAGE_NAME:-apgi-framework}:\${DOCKER_TAG:-latest}
    container_name: \${DOCKER_CONTAINER_NAME:-apgi-app}
    restart: unless-stopped
    
    environment:
      - APGI_ENV=\${APGI_ENV:-production}
      - APGI_DEBUG=\${APGI_DEBUG:-false}
      - APGI_LOG_LEVEL=\${APGI_LOG_LEVEL:-INFO}
      - APGUI_THEME=\${APGUI_THEME:-dark}
      - APGUI_FONT_SIZE=\${APGUI_FONT_SIZE:-12}
      - APGI_SECRET_KEY=\${APGI_SECRET_KEY}
      - APGI_MAX_WORKERS=\${APGI_MAX_WORKERS:-4}
      - APGI_THREAD_POOL_SIZE=\${APGI_THREAD_POOL_SIZE:-8}
    
    volumes:
      - ./data:/app/data
      - ./apgi_outputs:/app/apgi_outputs
      - ./session_state:/app/session_state
      - ./logs:/app/logs
      - ./figures:/app/figures
      - ./reports:/app/reports
    
    ports:
      - "8000:8000"
    
    networks:
      - apgi-network
    
    healthcheck:
      test: ["CMD", "python", "-c", "import apgi_framework; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # GUI support (if running with X11 forwarding)
    # environment:
    #   - DISPLAY=\${DISPLAY}
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
  # Optional: Redis for session management
  redis:
    image: redis:7-alpine
    container_name: apgi-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - apgi-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
  
  # Optional: PostgreSQL for production database
  postgres:
    image: postgres:15-alpine
    container_name: apgi-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=\${POSTGRES_DB:-apgi}
      - POSTGRES_USER=\${POSTGRES_USER:-apgi}
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - apgi-network
    ports:
      - "5432:5432"

networks:
  apgi-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
EOF
        print_status "Docker Compose file created: $COMPOSE_FILE"
    else
        print_status "Docker Compose file already exists: $COMPOSE_FILE"
    fi
}

# Function to build Docker image
build_image() {
    print_header "Building Docker Image"
    
    local tag="${1:-$DOCKER_TAG}"
    
    print_status "Building Docker image: $DOCKER_IMAGE_NAME:$tag"
    docker build -t "$DOCKER_IMAGE_NAME:$tag" .
    
    if [[ $? -eq 0 ]]; then
        print_status "Docker image built successfully"
    else
        print_error "Failed to build Docker image"
        exit 1
    fi
}

# Function to deploy application
deploy() {
    print_header "Deploying APGI Framework"
    
    # Stop existing container
    stop_container
    
    # Build new image
    build_image
    
    # Start services
    print_status "Starting services with Docker Compose..."
    docker-compose up -d
    
    if [[ $? -eq 0 ]]; then
        print_status "Application deployed successfully"
        print_status "Container name: $DOCKER_CONTAINER_NAME"
        print_status "Access logs with: docker-compose logs -f"
    else
        print_error "Failed to deploy application"
        exit 1
    fi
}

# Function to stop container
stop_container() {
    print_status "Stopping existing containers..."
    docker-compose down || true
    docker stop "$DOCKER_CONTAINER_NAME" 2>/dev/null || true
    docker rm "$DOCKER_CONTAINER_NAME" 2>/dev/null || true
}

# Function to show status
show_status() {
    print_header "Deployment Status"
    
    echo "Running containers:"
    docker-compose ps
    
    echo
    echo "Container logs (last 20 lines):"
    docker-compose logs --tail=20
    
    echo
    echo "Resource usage:"
    docker stats --no-stream "$DOCKER_CONTAINER_NAME" 2>/dev/null || print_warning "Container not running"
}

# Function to backup data
backup_data() {
    print_header "Backing Up Data"
    
    local backup_dir="backups/$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$backup_dir"
    
    # Backup application data
    if [[ -d "data" ]]; then
        cp -r data "$backup_dir/"
        print_status "Application data backed up"
    fi
    
    # Backup outputs
    if [[ -d "apgi_outputs" ]]; then
        cp -r apgi_outputs "$backup_dir/"
        print_status "Outputs backed up"
    fi
    
    # Backup session state
    if [[ -d "session_state" ]]; then
        cp -r session_state "$backup_dir/"
        print_status "Session state backed up"
    fi
    
    # Create compressed archive
    tar -czf "${backup_dir}.tar.gz" -C backups "$(basename "$backup_dir")"
    rm -rf "$backup_dir"
    
    print_status "Backup created: ${backup_dir}.tar.gz"
}

# Function to restore data
restore_data() {
    local backup_file="$1"
    
    if [[ -z "$backup_file" ]]; then
        print_error "Please specify backup file to restore"
        exit 1
    fi
    
    if [[ ! -f "$backup_file" ]]; then
        print_error "Backup file not found: $backup_file"
        exit 1
    fi
    
    print_header "Restoring Data from Backup"
    
    # Stop application first
    stop_container
    
    # Extract backup
    local temp_dir="restore_temp_$(date +%s)"
    mkdir -p "$temp_dir"
    tar -xzf "$backup_file" -C "$temp_dir"
    
    # Restore data
    local backup_name=$(basename "$backup_file" .tar.gz)
    if [[ -d "$temp_dir/$backup_name/data" ]]; then
        rm -rf data
        cp -r "$temp_dir/$backup_name/data" ./
        print_status "Application data restored"
    fi
    
    if [[ -d "$temp_dir/$backup_name/apgi_outputs" ]]; then
        rm -rf apgi_outputs
        cp -r "$temp_dir/$backup_name/apgi_outputs" ./
        print_status "Outputs restored"
    fi
    
    if [[ -d "$temp_dir/$backup_name/session_state" ]]; then
        rm -rf session_state
        cp -r "$temp_dir/$backup_name/session_state" ./
        print_status "Session state restored"
    fi
    
    # Cleanup
    rm -rf "$temp_dir"
    
    print_status "Data restored successfully"
    print_warning "Please restart the application"
}

# Function to update deployment
update_deployment() {
    print_header "Updating Deployment"
    
    # Pull latest code (if in git repository)
    if [[ -d ".git" ]]; then
        print_status "Pulling latest code..."
        git pull origin main || git pull origin master
    fi
    
    # Rebuild and redeploy
    deploy
}

# Function to show logs
show_logs() {
    local service="${1:-apgi-framework}"
    local lines="${2:-50}"
    
    print_status "Showing logs for $service (last $lines lines)..."
    docker-compose logs --tail="$lines" -f "$service"
}

# Function to health check
health_check() {
    print_header "Health Check"
    
    # Check if container is running
    if docker ps --filter "name=$DOCKER_CONTAINER_NAME" --quiet | grep -q .; then
        print_status "Container is running"
    else
        print_error "Container is not running"
        return 1
    fi
    
    # Check application health
    if docker exec "$DOCKER_CONTAINER_NAME" python -c "import apgi_framework; print('OK')" 2>/dev/null; then
        print_status "Application is healthy"
    else
        print_error "Application health check failed"
        return 1
    fi
    
    # Check resource usage
    print_status "Resource usage:"
    docker stats --no-stream "$DOCKER_CONTAINER_NAME"
}

# Function to cleanup
cleanup() {
    print_header "Cleaning Up"
    
    # Remove stopped containers
    docker container prune -f
    
    # Remove unused images
    docker image prune -f
    
    # Remove unused volumes (with confirmation)
    read -p "Remove unused Docker volumes? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        docker volume prune -f
    fi
    
    print_status "Cleanup completed"
}

# Function to show usage
show_usage() {
    echo "APGI Framework Deployment Script"
    echo
    echo "Usage: $0 [COMMAND] [OPTIONS]"
    echo
    echo "Commands:"
    echo "  deploy [tag]         Build and deploy application"
    echo "  stop                 Stop all containers"
    echo "  status               Show deployment status"
    echo "  logs [service] [n]   Show logs (default: 50 lines)"
    echo "  health               Perform health check"
    echo "  backup               Backup application data"
    echo "  restore <backup>     Restore from backup file"
    echo "  update               Update deployment with latest code"
    echo "  cleanup              Clean up Docker resources"
    echo "  init                 Initialize deployment configuration"
    echo
    echo "Examples:"
    echo "  $0 deploy            Deploy with latest tag"
    echo "  $0 deploy v1.0.0    Deploy with specific tag"
    echo "  $0 logs apgi-framework 100  Show last 100 log lines"
    echo "  $0 restore backup_20231201_120000.tar.gz"
}

# Main script logic
case "${1:-}" in
    "deploy")
        check_docker
        create_env_file
        create_compose_file
        deploy "${2:-}"
        ;;
    "stop")
        check_docker
        stop_container
        ;;
    "status")
        check_docker
        show_status
        ;;
    "logs")
        check_docker
        show_logs "${2:-}" "${3:-50}"
        ;;
    "health")
        check_docker
        health_check
        ;;
    "backup")
        backup_data
        ;;
    "restore")
        restore_data "$2"
        ;;
    "update")
        check_docker
        update_deployment
        ;;
    "cleanup")
        check_docker
        cleanup
        ;;
    "init")
        check_docker
        create_env_file
        create_compose_file
        print_status "Deployment configuration initialized"
        print_status "Run '$0 deploy' to deploy the application"
        ;;
    "--help"|"-h"|"help")
        show_usage
        ;;
    *)
        print_error "Unknown command: ${1:-}"
        show_usage
        exit 1
        ;;
esac
