@echo off
REM APGI Framework Deployment Script for Windows
REM Handles Docker deployment, environment setup, and service management

setlocal enabledelayedexpansion

REM Configuration
set DOCKER_IMAGE_NAME=apgi-framework
set DOCKER_CONTAINER_NAME=apgi-app
set DOCKER_TAG=latest
set ENVIRONMENT_FILE=.env
set COMPOSE_FILE=docker-compose.yml

echo [INFO] APGI Framework Deployment Script for Windows
echo ================================================

REM Function to check if Docker is available
:check_docker
docker --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker is not installed or not in PATH
    pause
    exit /b 1
)

docker compose version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker Compose v2 is not installed or not in PATH
    pause
    exit /b 1
)

echo [INFO] Docker and Docker Compose are available
goto :eof

REM Function to create environment file
:create_env_file
if not exist "%ENVIRONMENT_FILE%" (
    echo [INFO] Creating environment configuration file...
    (
        echo # APGI Framework Environment Configuration
        echo # Generated by deployment script on %date%
        echo.
        echo # Application Settings
        echo APGI_ENV=production
        echo APGI_DEBUG=false
        echo APGI_LOG_LEVEL=INFO
        echo.
        echo # Database Settings
        echo APGI_DB_PATH=/app/data/apgi.db
        echo APGI_DB_BACKUP_PATH=/app/data/backups/
        echo.
        echo # GUI Settings
        echo APGUI_THEME=dark
        echo APGUI_FONT_SIZE=12
        echo APGUI_WINDOW_WIDTH=1400
        echo APGUI_WINDOW_HEIGHT=900
        echo.
        echo # Security Settings
        echo APGI_SECRET_KEY=GENERATE_NEW_KEY_HERE
        echo APGI_SESSION_TIMEOUT=3600
        echo.
        echo # Performance Settings
        echo APGI_MAX_WORKERS=4
        echo APGI_THREAD_POOL_SIZE=8
        echo APGI_MEMORY_LIMIT=2g
        echo.
        echo # Data Paths
        echo APGI_DATA_DIR=/app/data
        echo APGI_OUTPUTS_DIR=/app/apgi_outputs
        echo APGI_SESSIONS_DIR=/app/session_state
        echo APGI_LOGS_DIR=/app/logs
    ) > "%ENVIRONMENT_FILE%"
    echo [INFO] Environment file created: %ENVIRONMENT_FILE%
    echo [WARNING] Please review and modify the environment variables as needed
) else (
    echo [INFO] Environment file already exists: %ENVIRONMENT_FILE%
)
goto :eof

REM Function to create Docker Compose file
:create_compose_file
if not exist "%COMPOSE_FILE%" (
    echo [INFO] Creating Docker Compose configuration...
    (
        echo version: '3.8'
        echo.
        echo services:
        echo   apgi-framework:
        echo     build:
        echo       context: .
        echo       dockerfile: Dockerfile
        echo     image: %DOCKER_IMAGE_NAME%:%DOCKER_TAG%
        echo     container_name: %DOCKER_CONTAINER_NAME%
        echo     restart: unless-stopped
        echo.
        echo     environment:
        echo       - APGI_ENV=production
        echo       - APGI_DEBUG=false
        echo       - APGI_LOG_LEVEL=INFO
        echo       - APGUI_THEME=dark
        echo       - APGUI_FONT_SIZE=12
        echo       - APGI_MAX_WORKERS=4
        echo       - APGI_THREAD_POOL_SIZE=8
        echo.
        echo     volumes:
        echo       - ./data:/app/data
        echo       - ./apgi_outputs:/app/apgi_outputs
        echo       - ./session_state:/app/session_state
        echo       - ./logs:/app/logs
        echo       - ./figures:/app/figures
        echo       - ./reports:/app/reports
        echo.
        echo     ports:
        echo       - "8000:8000"
        echo.
        echo     networks:
        echo       - apgi-network
        echo.
        echo     healthcheck:
        echo       test: ["CMD", "python", "-c", "import apgi_framework; print('OK')"]
        echo       interval: 30s
        echo       timeout: 10s
        echo       retries: 3
        echo       start_period: 40s
        echo.
        echo   redis:
        echo     image: redis:7-alpine
        echo     container_name: apgi-redis
        echo     restart: unless-stopped
        echo     volumes:
        echo       - redis_data:/data
        echo     networks:
        echo       - apgi-network
        echo     command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
        echo.
        echo networks:
        echo   apgi-network:
        echo     driver: bridge
        echo.
        echo volumes:
        echo   redis_data:
    ) > "%COMPOSE_FILE%"
    echo [INFO] Docker Compose file created: %COMPOSE_FILE%
) else (
    echo [INFO] Docker Compose file already exists: %COMPOSE_FILE%
)
goto :eof

REM Function to build Docker image
:build_image
echo [INFO] Building Docker image: %DOCKER_IMAGE_NAME%:%DOCKER_TAG%

if not exist "Dockerfile" (
    echo [ERROR] Dockerfile not found in current directory
    pause
    exit /b 1
)

docker build -t "%DOCKER_IMAGE_NAME%:%DOCKER_TAG%" .
if errorlevel 1 (
    echo [ERROR] Failed to build Docker image
    pause
    exit /b 1
)
echo [INFO] Docker image built successfully
goto :eof

REM Function to deploy application
:deploy
echo [INFO] Deploying APGI Framework...

REM Stop existing container
call :stop_container

REM Build new image
call :build_image

REM Start services
echo [INFO] Starting services with Docker Compose...
docker compose up -d
if errorlevel 1 (
    echo [ERROR] Failed to deploy application
    pause
    exit /b 1
)

echo [INFO] Application deployed successfully
echo [INFO] Container name: %DOCKER_CONTAINER_NAME%
echo [INFO] Access logs with: docker compose logs -f
goto :eof

REM Function to stop container
:stop_container
echo [INFO] Stopping existing containers...
docker compose down >nul 2>&1
goto :eof

REM Function to show status
:show_status
echo [INFO] Deployment Status
echo.
echo Running containers:
docker compose ps
echo.
echo Container logs ^(last 20 lines^):
docker compose logs --tail=20
goto :eof

REM Function to backup data
:backup_data
echo [INFO] Backing Up Data

for /f "tokens=2 delims==" %%a in ('wmic OS Get localdatetime /value') do set "dt=%%a"
set "YYYY=%dt:~0,4%"
set "MM=%dt:~4,2%"
set "DD=%dt:~6,2%"
set "HH=%dt:~8,2%"
set "Min=%dt:~10,2%"
set "Sec=%dt:~12,2%"
set "timestamp=%YYYY%%MM%%DD%_%HH%%Min%%Sec%"

set "backup_dir=backups\%timestamp%"
mkdir "%backup_dir%" 2>nul

REM Backup application data
if exist "data" (
    xcopy /E /I /Y data "%backup_dir%\data" >nul
    echo [INFO] Application data backed up
)

REM Backup outputs
if exist "apgi_outputs" (
    xcopy /E /I /Y apgi_outputs "%backup_dir%\apgi_outputs" >nul
    echo [INFO] Outputs backed up
)

REM Backup session state
if exist "session_state" (
    xcopy /E /I /Y session_state "%backup_dir%\session_state" >nul
    echo [INFO] Session state backed up
)

echo [INFO] Backup created: %backup_dir%
goto :eof

REM Function to show usage
:show_usage
echo APGI Framework Deployment Script for Windows
echo.
echo Usage: %0 [COMMAND]
echo.
echo Commands:
echo   deploy              Build and deploy application
echo   stop                Stop all containers
echo   status              Show deployment status
echo   logs                Show container logs
echo   backup              Backup application data
echo   init                Initialize deployment configuration
echo.
echo Examples:
echo   %0 deploy           Deploy application
echo   %0 status           Show deployment status
echo   %0 backup            Backup data
goto :eof

REM Main script logic
if "%1"=="deploy" (
    call :check_docker
    call :create_env_file
    call :create_compose_file
    call :deploy
) else if "%1"=="stop" (
    call :check_docker
    call :stop_container
) else if "%1"=="status" (
    call :check_docker
    call :show_status
) else if "%1"=="logs" (
    call :check_docker
    docker compose logs -f
) else if "%1"=="backup" (
    call :backup_data
) else if "%1"=="init" (
    call :check_docker
    call :create_env_file
    call :create_compose_file
    echo [INFO] Deployment configuration initialized
    echo [INFO] Run '%0 deploy' to deploy the application
) else if "%1"=="help" (
    call :show_usage
) else (
    echo [ERROR] Unknown command: %1
    echo.
    call :show_usage
    pause
    exit /b 1
)

pause
