[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True

[mypy-tests.*]
disallow_untyped_defs = False
disallow_untyped_calls = False
ignore_missing_imports = True

[mypy-apps.*]
disallow_untyped_defs = False
disallow_untyped_calls = False

[mypy-examples.*]
disallow_untyped_defs = False
disallow_untyped_calls = False

[mypy-apgi_framework.*]
disallow_untyped_defs = True
disallow_untyped_calls = True
warn_no_return = True

[mypy-core.*]
disallow_untyped_defs = True
disallow_untyped_calls = True
warn_no_return = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-seaborn.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-customtkinter.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-h5py.*]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-PySide6.*]
ignore_missing_imports = True
