import json
from typing import Dict, List

# Provided model metadata from user
MODEL_METADATA = {
    "mindfulness": [
        {
            "repo_id": "e-atoms/smollm-3b-awareness-thich-nhat-hanh-mindfulness-meditation-nondual-teaching",
            "likes": 2,
            "downloads": 11,
            "tags": [
                "gguf",
                "contemplative-ai",
                "fine-tuned",
                "nondual",
                "teaching",
                "spirituality",
                "awareness",
                "e-atoms",
                "meditation-agent",
                "v2",
                "smollm3",
                "thich-nhat-hanh",
                "text-generation",
                "en",
                "base_model:HuggingFaceTB/SmolLM3-3B-Base",
                "base_model:quantized:HuggingFaceTB/SmolLM3-3B-Base",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 23.13,
        }
    ],
    "creativity": [
        {
            "repo_id": "Undi95/CreativityEngine",
            "likes": 1,
            "downloads": 1041,
            "tags": [
                "transformers",
                "pytorch",
                "llama",
                "text-generation",
                "license:cc-by-nc-4.0",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 14.06,
        },
        {
            "repo_id": "mradermacher/Creativity-lfm2-5-350M-i1-GGUF",
            "likes": 0,
            "downloads": 2361,
            "tags": [
                "transformers",
                "gguf",
                "en",
                "dataset:wop/Extreme-Reasoning-CoT",
                "dataset:wop/Unlimited-Creativity-Chain-of-Thought",
                "base_model:wop/Creativity-lfm2-5-350M",
                "base_model:quantized:wop/Creativity-lfm2-5-350M",
                "license:mit",
                "endpoints_compatible",
                "region:us",
                "imatrix",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 12.36,
        },
        {
            "repo_id": "mradermacher/Creativity-lfm2-5-350M-GGUF",
            "likes": 0,
            "downloads": 469,
            "tags": [
                "transformers",
                "gguf",
                "en",
                "dataset:wop/Extreme-Reasoning-CoT",
                "dataset:wop/Unlimited-Creativity-Chain-of-Thought",
                "base_model:wop/Creativity-lfm2-5-350M",
                "base_model:quantized:wop/Creativity-lfm2-5-350M",
                "license:mit",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.47,
        },
        {
            "repo_id": "wop/Creativity-lfm2-5-350M",
            "likes": 2,
            "downloads": 232,
            "tags": [
                "safetensors",
                "gguf",
                "lfm2",
                "en",
                "dataset:wop/Extreme-Reasoning-CoT",
                "dataset:wop/Unlimited-Creativity-Chain-of-Thought",
                "base_model:LiquidAI/LFM2.5-350M",
                "base_model:quantized:LiquidAI/LFM2.5-350M",
                "license:mit",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.26,
        },
        {
            "repo_id": "Creativity0/m2m100_418M_ct2_int8",
            "likes": 0,
            "downloads": 74,
            "tags": [
                "base_model:facebook/m2m100_418M",
                "base_model:finetune:facebook/m2m100_418M",
                "license:mit",
                "region:us",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.07,
        },
        {
            "repo_id": "MIRERM/my-creativity",
            "likes": 1,
            "downloads": 7,
            "tags": [
                "diffusers",
                "safetensors",
                "NxtWave-GenAI-Webinar",
                "text-to-image",
                "stable-diffusion",
                "license:creativeml-openrail-m",
                "endpoints_compatible",
                "diffusers:StableDiffusionPipeline",
                "region:us",
            ],
            "pipeline_tag": "text-to-image",
            "last_modified": None,
            "score": 10.02,
        },
    ],
    "curiosity": [
        {
            "repo_id": "curiositytech/MARS",
            "likes": 8,
            "downloads": 7,
            "tags": [
                "transformers",
                "safetensors",
                "llama",
                "text-generation",
                "conversational",
                "tr",
                "en",
                "base_model:meta-llama/Meta-Llama-3-8B-Instruct",
                "base_model:finetune:meta-llama/Meta-Llama-3-8B-Instruct",
                "license:llama3",
                "model-index",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
                "deploy:azure",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.13,
        },
        {
            "repo_id": "curiositytech/MARS-v0.2",
            "likes": 5,
            "downloads": 16,
            "tags": [
                "safetensors",
                "llama",
                "text-generation",
                "conversational",
                "tr",
                "en",
                "base_model:meta-llama/Llama-3.1-8B-Instruct",
                "base_model:finetune:meta-llama/Llama-3.1-8B-Instruct",
                "license:llama3",
                "model-index",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.09,
        },
        {
            "repo_id": "Exploration/ppo-Huggy",
            "likes": 0,
            "downloads": 23,
            "tags": [
                "ml-agents",
                "tensorboard",
                "onnx",
                "Huggy",
                "deep-reinforcement-learning",
                "reinforcement-learning",
                "ML-Agents-Huggy",
                "region:us",
            ],
            "pipeline_tag": "reinforcement-learning",
            "last_modified": None,
            "score": 13.02,
        },
        {
            "repo_id": "AntimLabs/Qwen3.5-2B-Lumine-LoRA-exploration-object-examine-step-1296",
            "likes": 0,
            "downloads": 23,
            "tags": [
                "peft",
                "safetensors",
                "base_model:adapter:AntimLabs/Qwen3.5-2B-Lumine",
                "lora",
                "transformers",
                "text-generation",
                "arxiv:1910.09700",
                "base_model:AntimLabs/Qwen3.5-2B-Lumine",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.02,
        },
        {
            "repo_id": "AntimLabs/Qwen3.5-2B-Lumine-LoRA-exploration-object-examine",
            "likes": 0,
            "downloads": 17,
            "tags": [
                "peft",
                "safetensors",
                "base_model:adapter:AntimLabs/Qwen3.5-2B-Lumine",
                "lora",
                "transformers",
                "text-generation",
                "conversational",
                "arxiv:1910.09700",
                "base_model:AntimLabs/Qwen3.5-2B-Lumine",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.02,
        },
        {
            "repo_id": "imflash217/Pyramids_RND_Curiosity",
            "likes": 0,
            "downloads": 14,
            "tags": [
                "ml-agents",
                "tensorboard",
                "onnx",
                "unity-ml-agents",
                "deep-reinforcement-learning",
                "reinforcement-learning",
                "ML-Agents-Pyramids",
                "region:us",
            ],
            "pipeline_tag": "reinforcement-learning",
            "last_modified": None,
            "score": 13.01,
        },
    ],
    "hyperfocus": [
        {
            "repo_id": "lewtun/does-deepspeed-still-work-sft",
            "likes": 0,
            "downloads": 1,
            "tags": [
                "transformers",
                "safetensors",
                "qwen2",
                "text-generation",
                "generated_from_trainer",
                "open-r1",
                "trl",
                "sft",
                "conversational",
                "dataset:trl-lib/Capybara",
                "base_model:Qwen/Qwen2.5-1.5B",
                "base_model:finetune:Qwen/Qwen2.5-1.5B",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 3.0,
        },
        {
            "repo_id": "phdsilver22/counterfactual_generator-titanic-deepseek_r1_qwen_1.5B-worker",
            "likes": 0,
            "downloads": 5,
            "tags": ["peft", "safetensors", "arxiv:1910.09700", "region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 0.01,
        },
        {
            "repo_id": "phdsilver22/counterfactual_generator-california-deepseek_r1_qwen_1.5B-worker",
            "likes": 0,
            "downloads": 1,
            "tags": ["peft", "safetensors", "arxiv:1910.09700", "region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 0.0,
        },
        {
            "repo_id": "tsss1/DeepSeek_Q_Aprice_link_working_fine_4bitllma",
            "likes": 0,
            "downloads": 0,
            "tags": [
                "transformers",
                "safetensors",
                "text-generation-inference",
                "unsloth",
                "llama",
                "trl",
                "en",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 0.0,
        },
        {
            "repo_id": "huwar/deepseek_work_arrangements",
            "likes": 0,
            "downloads": 0,
            "tags": ["safetensors", "qwen2", "region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 0.0,
        },
        {
            "repo_id": "Foyer-work/npt-deepseek",
            "likes": 0,
            "downloads": 0,
            "tags": ["region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 0.0,
        },
    ],
    "inspiration": [
        {
            "repo_id": "HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive",
            "likes": 1274,
            "downloads": 1063984,
            "tags": [
                "gguf",
                "uncensored",
                "qwen3.5",
                "moe",
                "vision",
                "multimodal",
                "image-text-to-text",
                "en",
                "zh",
                "multilingual",
                "base_model:Qwen/Qwen3.5-35B-A3B",
                "base_model:quantized:Qwen/Qwen3.5-35B-A3B",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": "image-text-to-text",
            "last_modified": None,
            "score": 69.11,
        },
        {
            "repo_id": "HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive",
            "likes": 1113,
            "downloads": 905234,
            "tags": [
                "gguf",
                "uncensored",
                "qwen3.5",
                "qwen",
                "en",
                "zh",
                "multilingual",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 66.69,
        },
        {
            "repo_id": "HauhauCS/Qwen3.5-27B-Uncensored-HauhauCS-Aggressive",
            "likes": 294,
            "downloads": 358837,
            "tags": [
                "gguf",
                "uncensored",
                "qwen3.5",
                "qwen",
                "en",
                "zh",
                "multilingual",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 54.41,
        },
        {
            "repo_id": "HauhauCS/Gemma-4-E4B-Uncensored-HauhauCS-Aggressive",
            "likes": 286,
            "downloads": 486019,
            "tags": [
                "gguf",
                "uncensored",
                "gemma4",
                "abliterated",
                "vision",
                "multimodal",
                "audio",
                "image-text-to-text",
                "en",
                "multilingual",
                "license:gemma",
                "endpoints_compatible",
                "region:us",
                "imatrix",
                "conversational",
            ],
            "pipeline_tag": "image-text-to-text",
            "last_modified": None,
            "score": 54.29,
        },
        {
            "repo_id": "HauhauCS/Qwen3.5-4B-Uncensored-HauhauCS-Aggressive",
            "likes": 284,
            "downloads": 212235,
            "tags": [
                "gguf",
                "uncensored",
                "qwen3.5",
                "qwen",
                "en",
                "zh",
                "multilingual",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 54.26,
        },
        {
            "repo_id": "hatmimoha/arabic-ner",
            "likes": 22,
            "downloads": 348092,
            "tags": [
                "transformers",
                "pytorch",
                "tf",
                "jax",
                "safetensors",
                "bert",
                "token-classification",
                "ar",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "token-classification",
            "last_modified": None,
            "score": 50.33,
        },
    ],
    "fatigue": [
        {
            "repo_id": "keanteng/bert-fatigue-response-classification-wqd7005",
            "likes": 0,
            "downloads": 6,
            "tags": [
                "transformers",
                "safetensors",
                "bert",
                "text-classification",
                "healthcare",
                "risk-assessment",
                "questionnaire-analysis",
                "en",
                "base_model:google-bert/bert-base-uncased",
                "base_model:finetune:google-bert/bert-base-uncased",
                "license:agpl-3.0",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-classification",
            "last_modified": None,
            "score": 13.01,
        },
        {
            "repo_id": "RyanFan/Qwen2.5-1.5B-Instruct-RLCR-pmdata-fatigue",
            "likes": 0,
            "downloads": 4,
            "tags": [
                "transformers",
                "safetensors",
                "qwen2",
                "text-generation",
                "generated_from_trainer",
                "rl-verify",
                "conversational",
                "dataset:RyanFan/PMData-fatigue-raw-update",
                "arxiv:2402.03300",
                "base_model:Qwen/Qwen2.5-1.5B-Instruct",
                "base_model:finetune:Qwen/Qwen2.5-1.5B-Instruct",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.0,
        },
        {
            "repo_id": "RyanFan/Qwen3-1.7B-RLVR-pmdata-fatigue",
            "likes": 0,
            "downloads": 3,
            "tags": [
                "transformers",
                "safetensors",
                "qwen3",
                "text-generation",
                "generated_from_trainer",
                "trl",
                "grpo",
                "conversational",
                "arxiv:2402.03300",
                "base_model:Qwen/Qwen3-1.7B",
                "base_model:finetune:Qwen/Qwen3-1.7B",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.0,
        },
        {
            "repo_id": "RyanFan/RLVR-pmdata-fatigue",
            "likes": 0,
            "downloads": 1,
            "tags": [
                "transformers",
                "safetensors",
                "qwen2",
                "text-generation",
                "generated_from_trainer",
                "trl",
                "grpo",
                "conversational",
                "arxiv:2402.03300",
                "base_model:Qwen/Qwen2.5-1.5B-Instruct",
                "base_model:finetune:Qwen/Qwen2.5-1.5B-Instruct",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.0,
        },
        {
            "repo_id": "koyunC/Driver_Fatigue_Detection",
            "likes": 0,
            "downloads": 2,
            "tags": ["tflite", "license:apache-2.0", "region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.0,
        },
        {
            "repo_id": "xacer/vit-base-patch16-224-fatigue",
            "likes": 0,
            "downloads": 1,
            "tags": [
                "pytorch",
                "vit",
                "medical",
                "image-classification",
                "en",
                "base_model:google/vit-base-patch16-224",
                "base_model:finetune:google/vit-base-patch16-224",
                "license:mit",
                "region:us",
            ],
            "pipeline_tag": "image-classification",
            "last_modified": None,
            "score": 10.0,
        },
    ],
    "anxiety": [
        {
            "repo_id": "Ahatsham/Llama-3-8B-Instruct_Anxiety_Reasoning_Data-2",
            "likes": 0,
            "downloads": 5,
            "tags": [
                "transformers",
                "safetensors",
                "llama",
                "text-generation",
                "conversational",
                "arxiv:1910.09700",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.01,
        },
        {
            "repo_id": "mradermacher/Psychological_Counseling_Model_for_Occupational_Anxiety_in_Obese_Patients-i1-GGUF",
            "likes": 1,
            "downloads": 114,
            "tags": [
                "transformers",
                "gguf",
                "medical",
                "en",
                "base_model:jackxinning/Psychological_Counseling_Model_for_Occupational_Anxiety_in_Obese_Patients",
                "base_model:quantized:jackxinning/Psychological_Counseling_Model_for_Occupational_Anxiety_in_Obese_Patients",
                "license:mit",
                "endpoints_compatible",
                "region:us",
                "imatrix",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.13,
        },
        {
            "repo_id": "halilibr/dilbazlar-bert-uncased-anxiety-disorders-recognition-balanced-tr-model-acc-92.7",
            "likes": 1,
            "downloads": 4,
            "tags": ["safetensors", "bert", "license:apache-2.0", "region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.02,
        },
        {
            "repo_id": "mradermacher/Psychological_Counseling_Model_for_Occupational_Anxiety_in_Obese_Patients-GGUF",
            "likes": 0,
            "downloads": 10,
            "tags": [
                "transformers",
                "gguf",
                "medical",
                "en",
                "base_model:jackxinning/Psychological_Counseling_Model_for_Occupational_Anxiety_in_Obese_Patients",
                "base_model:quantized:jackxinning/Psychological_Counseling_Model_for_Occupational_Anxiety_in_Obese_Patients",
                "license:mit",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.01,
        },
        {
            "repo_id": "Mernaaaa/phi_athlete_anxiety_model",
            "likes": 0,
            "downloads": 4,
            "tags": ["gguf", "llama", "endpoints_compatible", "region:us", "conversational"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.0,
        },
        {
            "repo_id": "mradermacher/AnxietyModelFinal-Merged-GGUF",
            "likes": 0,
            "downloads": 4,
            "tags": [
                "transformers",
                "gguf",
                "en",
                "base_model:Ataraxia009/AnxietyModelFinal-Merged",
                "base_model:quantized:Ataraxia009/AnxietyModelFinal-Merged",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.0,
        },
    ],
    "fear": [
        {
            "repo_id": "fearlessdots/WizardLM-2-7B-abliterated",
            "likes": 15,
            "downloads": 109,
            "tags": [
                "transformers",
                "safetensors",
                "mistral",
                "text-generation",
                "arxiv:2304.12244",
                "arxiv:2306.08568",
                "arxiv:2308.09583",
                "license:apache-2.0",
                "text-generation-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-generation",
            "last_modified": None,
            "score": 13.33,
        },
        {
            "repo_id": "YoichiTakenaka/deverta-v3-japanese-large-Fear",
            "likes": 0,
            "downloads": 75,
            "tags": [
                "safetensors",
                "deberta-v2",
                "text-classification",
                "japanese",
                "license:cc-by-sa-4.0",
                "region:us",
            ],
            "pipeline_tag": "text-classification",
            "last_modified": None,
            "score": 13.07,
        },
        {
            "repo_id": "avichr/hebEMO_fear",
            "likes": 1,
            "downloads": 33,
            "tags": [
                "transformers",
                "pytorch",
                "bert",
                "text-classification",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-classification",
            "last_modified": None,
            "score": 13.05,
        },
        {
            "repo_id": "fearlessdots/WizardLM-2-7B-abliterated-GGUF",
            "likes": 8,
            "downloads": 92,
            "tags": [
                "gguf",
                "arxiv:2304.12244",
                "arxiv:2306.08568",
                "arxiv:2308.09583",
                "license:apache-2.0",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.21,
        },
        {
            "repo_id": "fearlessdots/Llama-3-Alpha-Centauri-v0.1-GGUF",
            "likes": 6,
            "downloads": 39,
            "tags": [
                "gguf",
                "dataset:NobodyExistsOnTheInternet/ToxicQAFinal",
                "license:llama3",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.13,
        },
        {
            "repo_id": "RichardErkhov/fearlessdots_-_WizardLM-2-7B-abliterated-gguf",
            "likes": 0,
            "downloads": 48,
            "tags": [
                "gguf",
                "arxiv:2304.12244",
                "arxiv:2306.08568",
                "arxiv:2308.09583",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.05,
        },
    ],
    "depression": [
        {
            "repo_id": "rafalposwiata/deproberta-large-depression",
            "likes": 9,
            "downloads": 546,
            "tags": [
                "transformers",
                "pytorch",
                "safetensors",
                "roberta",
                "text-classification",
                "depression",
                "en",
                "base_model:rafalposwiata/deproberta-large-v1",
                "base_model:finetune:rafalposwiata/deproberta-large-v1",
                "text-embeddings-inference",
                "endpoints_compatible",
                "deploy:azure",
                "region:us",
            ],
            "pipeline_tag": "text-classification",
            "last_modified": None,
            "score": 13.68,
        },
        {
            "repo_id": "paulagarciaserrano/roberta-depression-detection",
            "likes": 8,
            "downloads": 95,
            "tags": [
                "transformers",
                "pytorch",
                "roberta",
                "text-classification",
                "en",
                "text-embeddings-inference",
                "endpoints_compatible",
                "region:us",
                "deploy:azure",
            ],
            "pipeline_tag": "text-classification",
            "last_modified": None,
            "score": 13.21,
        },
        {
            "repo_id": "rafalposwiata/roberta-large-depression",
            "likes": 1,
            "downloads": 89,
            "tags": [
                "transformers",
                "pytorch",
                "safetensors",
                "roberta",
                "text-classification",
                "depression",
                "en",
                "base_model:FacebookAI/roberta-large",
                "base_model:finetune:FacebookAI/roberta-large",
                "text-embeddings-inference",
                "endpoints_compatible",
                "region:us",
            ],
            "pipeline_tag": "text-classification",
            "last_modified": None,
            "score": 13.1,
        },
        {
            "repo_id": "TTahir/Llama8b_CBT_Depression_Finetune_Nov_4",
            "likes": 3,
            "downloads": 117,
            "tags": ["safetensors", "gguf", "llama", "endpoints_compatible", "region:us"],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.16,
        },
        {
            "repo_id": "mradermacher/Qwen-1.8B-8bit_DepressionDetection-GGUF",
            "likes": 0,
            "downloads": 55,
            "tags": [
                "transformers",
                "gguf",
                "llama-factory",
                "en",
                "base_model:Moriacrafter/Qwen-1.8B-8bit_DepressionDetection",
                "base_model:quantized:Moriacrafter/Qwen-1.8B-8bit_DepressionDetection",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.05,
        },
        {
            "repo_id": "mradermacher/Qwen1.5-4B-none_DepressionDetection_Reddit-GGUF",
            "likes": 0,
            "downloads": 53,
            "tags": [
                "transformers",
                "gguf",
                "llama-factory",
                "en",
                "base_model:Moriacrafter/Qwen1.5-4B-none_DepressionDetection_Reddit",
                "base_model:quantized:Moriacrafter/Qwen1.5-4B-none_DepressionDetection_Reddit",
                "endpoints_compatible",
                "region:us",
                "conversational",
            ],
            "pipeline_tag": None,
            "last_modified": None,
            "score": 10.05,
        },
    ],
}


def get_model_metadata() -> Dict[str, List[Dict[str, object]]]:
    return MODEL_METADATA


def save_to_cache(file_path: str = "apgi_hf_cache.json") -> None:
    cache_data = {
        "timestamp": 1776087211.490595,  # Keep original timestamp or update
        "data": MODEL_METADATA,
    }
    with open(file_path, "w") as f:
        json.dump(cache_data, f, indent=2)


if __name__ == "__main__":
    save_to_cache()
    print("✅ Created/Updated apgi_hf_cache.json with provided model data.")
